Handle GPTs on FreeBSD images.

diff --git a/clientside/tmcc/linux/slicefix b/clientside/tmcc/linux/slicefix
--- a/clientside/tmcc/linux/slicefix
+++ b/clientside/tmcc/linux/slicefix
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright (c) 2000-2021 University of Utah and the Flux Group.
+# Copyright (c) 2000-2022 University of Utah and the Flux Group.
 # 
 # {{{EMULAB-LICENSE
 # 
@@ -44,7 +44,7 @@ if [ $OS = FreeBSD ]; then
     fi    
 fi
 
-freebsd_disk="ad0"
+freebsd_disk="ada0"
 
 case $# in
 1)
@@ -63,10 +63,19 @@ linux_disk=`$BINDIR/freebsd_to_linux_disk $freebsd_disk`
 old_linux_disk=${linux_disk#* }
 linux_disk=${linux_disk%% *}
 
+isgpt=0
 if [ $OS = Linux ]; then
 	disk=$linux_disk
+	if fdisk -l /dev/$disk 2>/dev/null | grep -qi 'found valid gpt'; then
+		isgpt=1
+		freebsd_pchar=p
+	fi
 elif [ $OS = FreeBSD ]; then
 	disk=$freebsd_disk
+	if gpart show $freebsd_disk 2>/dev/null | grep -q GPT; then
+		isgpt=1
+		freebsd_pchar=p
+	fi
 fi
 
 #
@@ -144,7 +153,7 @@ fi
 DISABLEIF=$SLICEFIX_DISABLEIF
 DISABLEHINT=
 if [ -n "$DISABLEIF" ]; then
-    _str=`echo $DISABLEIF | sed -e 's/^([a-zA-Z0-9]*[a-zA-Z])([0-9][0-9]*)/hint.\1.\2.disabled/'`
+    _str=`echo $DISABLEIF | sed -E -e 's/^([a-zA-Z0-9]*[a-zA-Z])([0-9]+)/hint.\1.\2.disabled/'`
     if [ "$_str" = "$DISABLEIF" ]; then
 	echo "WARNING: unparsable define name \"$DISABLEIF\" ignored"
     else
@@ -285,8 +294,12 @@ dofixauthkeys() {
 	if [ ! -d /mnt/root/.ssh ]; then
 	    return 1
 	fi
-	if [ -x /usr/bin/stat ]; then
-	    _stat=`/usr/bin/stat -f '%u,%g,%p' /mnt/root/.ssh`
+	if [ -x /bin/stat -o -x /usr/bin/stat ]; then
+	    if [ $OS = Linux ]; then
+		_stat=`/bin/stat -c '%u,%g,40%a' /mnt/root/.ssh`
+	    else
+		_stat=`/usr/bin/stat -f '%u,%g,%p' /mnt/root/.ssh`
+	    fi
 	    if [ "$_stat" != "0,0,40700" ]; then
 		return 1
 	    fi
@@ -434,41 +447,8 @@ EOF8
 }
 
 dofreebsd() {
-	#
-	# ARGH!  FreeBSD 5, which primarily uses UFS2, internally converts
-	# UFS1 filesystems to an updated, UFS2 compatible form.  However,
-	# some of the converted fields leak back to disk when the filesystem
-	# is unmounted, creating the potential for corruption in the following
-	# scenerio:
-	#
-	# 1. mount, update, and unmount a UFS1 FS under FBSD5
-	# 2. mount, update, and unmount the FS under FBSD4
-	# 3. go back and access the FS under FBSD5
-	#
-	# #2 will update the old version of the csum structure.  At step
-	# #3, the mount will see some of the leaked info from the unmount
-	# in #1 and determine that it has already "upgraded" this FS and
-	# thus doesn't need to copy the old csum into the new one.  The
-	# result is that it will use stale csum info.
-	#
-	# In theory we could encounter this problem when we slicefix
-	# a newly loaded FBSD image (#1), boot up and update stuff on
-	# the image (#2), and then create a new image with imagezip
-	# (#3, as imagezip uses the FBSD5 filesystem logic).
-	#
-	# How do we deal with this?  What we will have to do is either
-	# fix the FBSD5 filesystem code or we will have to run a little
-	# hack after the slicefix unmount to undo the damage that FBSD5
-	# does.  Currently I have not done either.  Instead we avoid the
-	# problem as follows.  Before making any change to the FS with
-	# slicefix, we first RO-mount the FS to see if anything needs to
-	# be done.  If not, we just leave it alone.  Since I currently
-	# create all new images on machines with "ad" disks and that is
-	# what the default fstab contains for its root device, we avoid
-	# making any mods with slicefix and thus avoid #1 above.
-	#
-	# This is clearly not a solution.
-	#
+	pchar=$freebsd_pchar
+
 	if [ $OS = FreeBSD ]; then
 		vers=`uname -v | sed -e 's/FreeBSD \([0-9]\).*/\1/'`
 
@@ -477,8 +457,12 @@ dofreebsd() {
 			return 1
 		}
 
-		rootdev=/dev/${disk}s${part}a
-		echo "fixing FreeBSD root partition ${disk}s${part}a"
+		if [ $isgpt -eq 0 ]; then
+			rootdev=/dev/${disk}s${part}a
+		else
+			rootdev=/dev/${disk}p${part}
+		fi
+		echo "fixing FreeBSD root partition $rootdev"
 		fsck -p $rootdev || {
 			# 8.x fsck fails to determine the FS type, try again with ufs
 			echo "retrying fsck with '-t ufs'"
@@ -497,7 +481,11 @@ dofreebsd() {
 		else
 			echo w | /sbin/fdisk /dev/$disk > /dev/null 2>&1
 		fi
-		rootdev=/dev/`$BINDIR/check_disklabel $disk $part`
+
+		rootdev=/dev/
+		if [ $isgpt -eq 0 ]; then
+			rootdev=/dev/`$BINDIR/check_disklabel $disk $part`
+		fi
 		#
 		# XXX Linux seems to no longer detect the BSD disk label
 		# when there is a single BSD partition. For all our recent
@@ -542,6 +530,7 @@ dofreebsd() {
 	changesshd=0
 	changeauth=0
 	changercert=0
+	changelconf=0
 
 	fixit=0
 
@@ -556,7 +545,7 @@ dofreebsd() {
 	fi
 
 	# If our disk/part does not appear anywhere in fstab, we need to fix it
-	grep "^/dev/${freebsd_disk}s${part}" /mnt/etc/fstab >/dev/null 2>&1
+	grep "^/dev/${freebsd_disk}${pchar}${part}" /mnt/etc/fstab >/dev/null 2>&1
 	case $? in
 	0)
 	    ;;
@@ -596,6 +585,7 @@ dofreebsd() {
 		*)
 		    if [ $ACPI = "yes" ]; then
 			changeacpi=1
+			changelconf=1
 			fixit=1
 		    fi
 		    ;;
@@ -621,12 +611,14 @@ dofreebsd() {
 		0)
 		    if [ $ASF = "no" ]; then
 			changeasf=1
+			changelconf=1
 			fixit=1
 		    fi
 		    ;;
 		*)
 		    if [ $ASF = "yes" ]; then
 			changeasf=1
+			changelconf=1
 			fixit=1
 		    fi
 		    ;;
@@ -640,6 +632,7 @@ dofreebsd() {
 	fi
 
 	if [ $NOCLFLUSH != "unknown" ]; then
+	    changelconf=1
 	    fixit=1
 	fi
 
@@ -651,6 +644,7 @@ dofreebsd() {
 	null|vid)
 	    if [ "$curconsole" != "${CONSOLE}console" ]; then
 		changecons=1
+		changelconf=1
 		fixit=1
 	    fi
 	    ;;
@@ -658,6 +652,7 @@ dofreebsd() {
 	    if [ "$curconsole" != "comconsole" ]; then
 		# not comconsole, fix it
 		changecons=1
+		changelconf=1
 		fixit=1
 	    else
 		# see if the com port has changed
@@ -668,6 +663,7 @@ dofreebsd() {
 		fi
 		if [ "$flags" != "0x10" ]; then
 		    changecons=1
+		    changelconf=1
 		    fixit=1
 		fi
 	    fi
@@ -778,6 +774,27 @@ dofreebsd() {
 		return 0
 	fi
 
+	if [ 0 -eq 1 ]; then
+		echo changedisk=$changedisk
+		echo changeentropy=$changeentropy
+		echo changeacpi=$changeacpi
+		echo changeasf=$changeasf
+		echo changeclflush=$changeclflush
+		echo changecons=$changecons
+		echo changecerts=$changecerts
+		echo changehostkeys=$changehostkeys
+		echo changerootkeys=$changerootkeys
+		echo changezone=$changezone
+		echo changentp=$changentp
+		echo changechrony=$changechrony
+		echo changesshd=$changesshd
+		echo changeauth=$changeauth
+		echo changercert=$changercert
+		echo changelconf=$changelconf
+		umount $rootdev
+		return 0
+	fi
+
 	# We need to change something, remount RW and change it
 	if [ $OS = FreeBSD ]; then
 		umount $rootdev
@@ -806,16 +823,27 @@ dofreebsd() {
 	    if [ -f /mnt/etc/fstab ]; then
 	    	    echo "  updating /etc/fstab"
 		    cp -fp /mnt/etc/fstab /mnt/etc/fstab.preemulab
-		    sed -i -e "s;^/dev/[a-zA-Z][a-zA-Z]*[0-9][0-9]*s[0-9][0-9]*;/dev/${freebsd_disk}s${part};" /mnt/etc/fstab || {
-			echo "Failed to update /etc/fstab"
-			umount $rootdev
-			return 1
-		    }
+		    if [ $isgpt -ne 0 ]; then
+			# XXX for GPT we need to remove any BSD partition specifier
+			# There should only be a root partition specified.
+			sed -i -E -e "s;^/dev/[a-zA-Z]+[0-9]+[sp][0-9]+[a-z]*;/dev/${freebsd_disk}${pchar}${part};" /mnt/etc/fstab || {
+			    echo "Failed to update /etc/fstab"
+			    umount $rootdev
+			    return 1
+			}
+		    else
+			# XXX otherwise we need to leave any BSD partition specifier
+			sed -i -E -e "s;^/dev/[a-zA-Z]+[0-9]+[sp][0-9]+([a-z]*);/dev/${freebsd_disk}${pchar}${part}\1;" /mnt/etc/fstab || {
+			    echo "Failed to update /etc/fstab"
+			    umount $rootdev
+			    return 1
+			}
+		    fi
     	    fi
 	    if [ -f /mnt/etc/dumpdates ]; then
 		    echo "  updating /etc/dumpdates"
 		    cp -fp /mnt/etc/dumpdates /mnt/etc/dumpdates.preemulab
-		    sed -i -e "s;^/dev/[a-zA-Z][a-zA-Z]*[0-9][0-9]*s[0-9][0-9]*;/dev/${freebsd_disk}s${part};" /mnt/etc/dumpdates || {
+		    sed -i -E -e "s;^/dev/[a-zA-Z]+[0-9]+[sp][0-9]+;/dev/${freebsd_disk}${pchar}${part};" /mnt/etc/dumpdates || {
 			echo "WARNING: Failed to update /etc/dumpdates"
 		    }
 	    fi
@@ -844,10 +872,12 @@ dofreebsd() {
 	cp -p /mnt/boot/loader.conf /mnt/boot/loader.conf.preemulab || {
 	    echo "WARNING: could not create a copy of loader.conf"
 	}
-	cat <<EOF4 >>/mnt/boot/loader.conf
+	if [ $changelconf -eq 1 ]; then
+	    cat <<EOF4 >>/mnt/boot/loader.conf
 # The remaining lines were added by Emulab slicefix.
 # DO NOT ADD ANYTHING AFTER THIS POINT AS IT WILL GET REMOVED.
 EOF4
+	fi
 
 	if [ $changeacpi -eq 1 ]; then
 	    if [ $ACPI = "no" ]; then
@@ -1088,14 +1118,6 @@ EOF1
 	fi
 
 	umount $rootdev
-	if [ $OS = FreeBSD ]; then
-		# XXX need to fixup FS, see big comment above
-		if [ "x$vers" != "x4" ]; then
-			echo "WARNING: FBSD${vers} may have modified the UFS1 root FS"
-		fi
-
-	fi
-
 	return 0
 }
 
@@ -1134,14 +1156,13 @@ dolinux() {
 
 fixone() {
     if [ $OS = FreeBSD ]; then
-    	echo "*** ${disk}s${part}:"
+    	echo "*** ${disk}${freebsd_pchar}${part}:"
     	ptype=`fdisk -${part} ${disk} | grep sysid | sed 's/^sysid \([0-9][0-9]*\).*/\1/'`
     elif [ $OS = Linux ]; then
 	fullpath=${disk}${part}
 	(echo ${disk} | grep -q ^nvme) && fullpath=${disk}p${part}
     	echo "*** ${fullpath}:"
-	fdisk -l /dev/$disk | grep -qi 'found valid gpt'
-	if [ $? -eq 0 ]; then
+	if [ $isgpt -ne 0 ]; then
 	    # gdisk output converts the gpt partition ID to, e.g., 8300.
 	    ptype=`gdisk -l /dev/$disk | awk "/^ *${part} / {print \\$6}"`
 	else
@@ -1151,7 +1172,7 @@ fixone() {
     ptype=${ptype:-0}
 
     case $ptype in
-    165|0xa5)
+    165|0xa5|A503)
 	dofreebsd
 	return $?
 	;;
@@ -1159,7 +1180,7 @@ fixone() {
 	dolinux
 	return $?
 	;;
-    130|0x82)
+    130|0x82|8200)
 	echo "ignoring Linux swap partition"
 	;;
     7|0x7)
@@ -1167,6 +1188,12 @@ fixone() {
 	;;
     0|0x0)
 	echo "ignoring unused partition"
+	;;
+    EF00)
+	echo "ignoring EFI partition"
+	;;
+    A501)
+	echo "ignoring FreeBSD boot partition"
 	;;
     *)
 	echo "ignoring partition type $ptype"
