Add chrony support for CentOS 8; no ntpd there.

diff --git a/clientside/tmcc/freebsd/slicefix b/clientside/tmcc/freebsd/slicefix
--- a/clientside/tmcc/freebsd/slicefix
+++ b/clientside/tmcc/freebsd/slicefix
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright (c) 2000-2018 University of Utah and the Flux Group.
+# Copyright (c) 2000-2019 University of Utah and the Flux Group.
 # 
 # {{{EMULAB-LICENSE
 # 
@@ -488,6 +488,7 @@ dofreebsd() {
 	changerootkeys=0
 	changezone=0
 	changentp=0
+	changechrony=0
 	changesshd=0
 	changeauth=0
 
@@ -680,6 +681,15 @@ dofreebsd() {
 		cmp -s /etc/ntp.conf /mnt/etc/ntp.conf
 		if [ $? -ne 0 ]; then
 		    changentp=1
+		    fixit=1
+		fi
+	    fi
+
+	    # Check the chrony config.
+	    if [ -e /etc/chrony.conf ]; then
+		cmp -s /etc/chrony.conf /mnt/etc/chrony.conf
+		if [ $? -ne 0 ]; then
+		    changechrony=1
 		    fixit=1
 		fi
 	    fi
@@ -962,6 +972,17 @@ EOF1
 
 	    cp -p /etc/ntp.conf /mnt/etc/ntp.conf || {
 	        echo "Failed to create /etc/ntp.conf"
+		umount $rootdev
+		return 1
+	    }
+	fi
+
+	# Copy in new chrony config
+	if [ $changechrony -eq 1 ]; then
+	    echo "  updating /etc/chrony.conf"
+
+	    cp -p /etc/chrony.conf /mnt/etc/chrony.conf || {
+	        echo "Failed to create /etc/chrony.conf"
 		umount $rootdev
 		return 1
 	    }
diff --git a/clientside/tmcc/linux/slicefix b/clientside/tmcc/linux/slicefix
--- a/clientside/tmcc/linux/slicefix
+++ b/clientside/tmcc/linux/slicefix
@@ -526,6 +526,7 @@ dofreebsd() {
 	changerootkeys=0
 	changezone=0
 	changentp=0
+	changechrony=0
 	changesshd=0
 
 	fixit=0
@@ -716,6 +717,15 @@ dofreebsd() {
 		cmp -s /etc/ntp.conf /mnt/etc/ntp.conf
 		if [ $? -ne 0 ]; then
 		    changentp=1
+		    fixit=1
+		fi
+	    fi
+
+	    # Check the chrony config.
+	    if [ -e /etc/chrony.conf ]; then
+		cmp -s /etc/chrony.conf /mnt/etc/chrony.conf
+		if [ $? -ne 0 ]; then
+		    changechrony=1
 		    fixit=1
 		fi
 	    fi
@@ -1011,6 +1021,17 @@ EOF1
 
 	    cp -p /etc/ntp.conf /mnt/etc/ntp.conf || {
 	        echo "Failed to create /etc/ntp.conf"
+		umount $rootdev
+		return 1
+	    }
+	fi
+
+	# Copy in new chrony config
+	if [ $changechrony -eq 1 ]; then
+	    echo "  updating /etc/chrony.conf"
+
+	    cp -p /etc/chrony.conf /mnt/etc/chrony.conf || {
+	        echo "Failed to create /etc/chrony.conf"
 		umount $rootdev
 		return 1
 	    }
